<#
.SYNOPSIS
  Read-only schema discovery for the JADI staging database (Spec Sec.15 "validate table/view names
  during discovery"; ASSUMPTIONS A-2, A-4, A-16, Q5).

.DESCRIPTION
  Connects with the built-in .NET SQL client and writes a Markdown report to docs/discovery/.
  It reads ONLY:
    - catalog metadata (tables, views, columns, data types, view definitions)
    - aggregate counts and distinct code values (statuses, classification codes, operator codes,
      term identifiers)
  It never selects student rows, names, IDs, emails, PIDs, or balances for individual students.

  Connection details come from the user's environment, never from the command line or chat:
    JADI_STAGING_SERVER     e.g. SQLSTAGE01 or SQLSTAGE01\INSTANCE or host,1433
    JADI_STAGING_DATABASE   e.g. ousadb
    JADI_STAGING_USER       SQL login (read-only)
    JADI_STAGING_PASSWORD   SQL login password
    JADI_STAGING_ENCRYPT    optional: True | False   (default False for on-prem staging)

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts\discover-schema.ps1
#>
[CmdletBinding()]
param(
  [string]$OutDir = (Join-Path $PSScriptRoot "..\docs\discovery")
)

$ErrorActionPreference = "Stop"

function Require-Env([string]$name) {
  $v = [Environment]::GetEnvironmentVariable($name, "User")
  if (-not $v) { $v = [Environment]::GetEnvironmentVariable($name, "Process") }
  if (-not $v) { throw "Environment variable $name is not set (set it in your Windows user environment)." }
  return $v
}

$server   = Require-Env "JADI_STAGING_SERVER"
$database = Require-Env "JADI_STAGING_DATABASE"
$user     = Require-Env "JADI_STAGING_USER"
$password = Require-Env "JADI_STAGING_PASSWORD"
$encrypt  = [Environment]::GetEnvironmentVariable("JADI_STAGING_ENCRYPT", "User"); if (-not $encrypt) { $encrypt = "False" }

$builder = New-Object System.Data.SqlClient.SqlConnectionStringBuilder
$builder["Data Source"] = $server
$builder["Initial Catalog"] = $database
$builder["User ID"] = $user
$builder["Password"] = $password
$builder["Encrypt"] = [bool]::Parse($encrypt)
$builder["TrustServerCertificate"] = $true
$builder["Application Name"] = "JADI-Dashboard-Discovery"
$builder["Connect Timeout"] = 20
$builder["ApplicationIntent"] = "ReadOnly"

$conn = New-Object System.Data.SqlClient.SqlConnection($builder.ConnectionString)
$conn.Open()
# Belt and braces: even though the login should be read-only, refuse to write in this session.
$null = (New-Object System.Data.SqlClient.SqlCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;", $conn)).ExecuteNonQuery()

$sb = New-Object System.Text.StringBuilder
function Out([string]$s) { [void]$sb.AppendLine($s) }

function Query([string]$title, [string]$sql, [int]$maxRows = 500) {
  Out ""
  Out "### $title"
  Out ""
  Out '```sql'
  Out $sql.Trim()
  Out '```'
  Out ""
  Write-Host ("[{0:HH:mm:ss}] {1}" -f (Get-Date), $title)
  try {
    $cmd = New-Object System.Data.SqlClient.SqlCommand($sql, $conn)
    $cmd.CommandTimeout = 45
    $da = New-Object System.Data.SqlClient.SqlDataAdapter($cmd)
    $dt = New-Object System.Data.DataTable
    [void]$da.Fill($dt)
    if ($dt.Rows.Count -eq 0) { Out "_no rows_"; return }
    $cols = $dt.Columns | ForEach-Object { $_.ColumnName }
    Out ("| " + ($cols -join " | ") + " |")
    Out ("|" + (($cols | ForEach-Object { "---" }) -join "|") + "|")
    $n = 0
    foreach ($row in $dt.Rows) {
      $vals = foreach ($c in $cols) { $v = $row[$c]; if ($v -is [DBNull]) { "NULL" } else { ($v.ToString() -replace "\r?\n", " " -replace "\|", "\|") } }
      Out ("| " + ($vals -join " | ") + " |")
      if (++$n -ge $maxRows) { Out "| _... truncated at $maxRows rows_ |"; break }
    }
    Out ""
    Out "_$($dt.Rows.Count) row(s)_"
  } catch {
    Out "**ERROR:** $($_.Exception.Message)"
  }
}

$stamp = Get-Date -Format "yyyy-MM-dd_HHmm"
Out "# ousadb schema discovery - $stamp"
Out ""
Out "Server: (redacted - see JADI_STAGING_SERVER) | Database: **$database** | Login: (redacted) | Encrypt: $encrypt"
Out ""
Out "Metadata and aggregates only. No student-level rows were read. Generated by scripts/discover-schema.ps1."
Out ""
Out "## 1. Server and database"
Query "Version" "SELECT @@VERSION AS version, DB_NAME() AS db, SUSER_SNAME() AS login_name;"
Query "Login permissions (should be read-only)" @"
SELECT dp.permission_name COLLATE DATABASE_DEFAULT AS name, dp.state_desc COLLATE DATABASE_DEFAULT AS state_desc, dp.class_desc COLLATE DATABASE_DEFAULT AS class_desc
FROM sys.database_permissions dp
WHERE dp.grantee_principal_id = DATABASE_PRINCIPAL_ID()
UNION ALL
SELECT r.name COLLATE DATABASE_DEFAULT, 'ROLE MEMBER', 'DATABASE_ROLE'
FROM sys.database_role_members m JOIN sys.database_principals r ON r.principal_id = m.role_principal_id
WHERE m.member_principal_id = DATABASE_PRINCIPAL_ID()
UNION ALL
SELECT 'IS_SRVROLEMEMBER(sysadmin)', CAST(IS_SRVROLEMEMBER('sysadmin') AS varchar(1)), 'SERVER_ROLE';
"@

Out ""
Out "## 2. Objects"
Query "All tables and views" @"
SELECT s.name AS [schema], o.name AS [object], o.type_desc,
       (SELECT COUNT(*) FROM sys.columns c WHERE c.object_id = o.object_id) AS column_count
FROM sys.objects o JOIN sys.schemas s ON s.schema_id = o.schema_id
WHERE o.type IN ('U','V')
ORDER BY o.type_desc, s.name, o.name;
"@
Query "Objects of interest (name match)" @"
SELECT s.name AS [schema], o.name AS [object], o.type_desc
FROM sys.objects o JOIN sys.schemas s ON s.schema_id = o.schema_id
WHERE o.type IN ('U','V') AND (
     o.name LIKE '%ourm%' OR o.name LIKE '%acad%' OR o.name IN ('tblStudent','tblOUSA')
  OR o.name LIKE '%clear%' OR o.name LIKE '%trans_hist%' OR o.name LIKE '%worksheet%')
ORDER BY o.name;
"@

Out ""
Out "## 3. Columns of objects of interest"
Query "Columns" @"
SELECT o.name AS [object], c.column_id AS ord, c.name AS [column],
       t.name AS type, c.max_length, c.precision, c.scale, c.is_nullable
FROM sys.columns c
JOIN sys.objects o ON o.object_id = c.object_id
JOIN sys.types t ON t.user_type_id = c.user_type_id
WHERE o.name LIKE '%ourm%' OR o.name LIKE '%acad%' OR o.name IN ('tblStudent','tblOUSA')
ORDER BY o.name, c.column_id;
"@ 2000

Out ""
Out "## 4. View definitions (SQL text - no data)"
Query "View definitions" @"
SELECT o.name AS [view], m.definition
FROM sys.sql_modules m JOIN sys.objects o ON o.object_id = m.object_id
WHERE (o.type = 'V' AND (o.name LIKE '%ourm%' OR o.name LIKE '%acad%' OR o.name LIKE 'VIEW_LAST%' OR o.name LIKE 'VIEW_OUSA%'))
   OR (o.type IN ('FN','IF','TF') AND o.name LIKE 'fn_%')
ORDER BY o.name;
"@

Out ""
Out "## 5. Term metadata (tblOUSA is institutional metadata, not student data)"
Query "tblOUSA contents" "SELECT * FROM dbo.tblOUSA;" 200

Out ""
Out "## 6. Aggregates for Spec Sec.6 (counts only)"
Query "Enrolled via VIEW_OURM (fast path; FCA times out)" @"
SELECT COUNT(*) AS enrolled_rows, COUNT(DISTINCT idnumber) AS enrolled_distinct,
       SUM(CASE WHEN ClearedCurrentSession = 1 THEN 1 ELSE 0 END) AS cleared_flag_count,
       SUM(CASE WHEN ClearedCurrentSession = 1 THEN 0 ELSE 1 END) AS not_cleared_flag_count
FROM dbo.VIEW_OURM;
"@
Query "tblStudent.ClearedCurrentSession distribution" "SELECT ClearedCurrentSession, COUNT(*) AS n FROM dbo.tblStudent GROUP BY ClearedCurrentSession;"
Query "Cleared (view_ourm_stats rows = 1)" "SELECT COUNT(*) AS cleared_rows, COUNT(DISTINCT idnumber) AS cleared_distinct FROM dbo.VIEW_OURM_STATS WHERE [rows] = 1;"
Query "Classification codes in VIEW_OURM_STATS (Class = CURRENT_CLASS_CDE) with 'what' text (Sec.7.3)" "SELECT Class, what, COUNT(*) AS n FROM dbo.VIEW_OURM_STATS WHERE [rows] = 1 GROUP BY Class, what ORDER BY n DESC;"
Query "Classification codes (cCode) across enrolled students via VIEW_OURM join student_master" @"
SELECT ISNULL(SM.CURRENT_CLASS_CDE,'XX') AS cCode, SM.TEL_WEB_GRP_CDE, COUNT(*) AS n
FROM dbo.VIEW_OURM V JOIN [jadi].[dbo].[student_master] SM ON CAST(SM.ID_NUM AS varchar) = V.idnumber
GROUP BY ISNULL(SM.CURRENT_CLASS_CDE,'XX'), SM.TEL_WEB_GRP_CDE ORDER BY n DESC;
"@
Query "ClearedBy operator codes (Sec.7.2)" "SELECT ClearedBy, COUNT(*) AS n, MIN(DateCleared) AS first_seen, MAX(DateCleared) AS last_seen FROM dbo.VIEW_OURM_STATS WHERE [rows] = 1 GROUP BY ClearedBy ORDER BY n DESC;"
Query "Cleared by date (current term, for Sec.7.1 shape check)" "SELECT CAST(DateCleared AS date) AS d, COUNT(*) AS n FROM dbo.VIEW_OURM_STATS WHERE [rows] = 1 GROUP BY CAST(DateCleared AS date) ORDER BY d;" 200
Query "Charges / credits totals and dcd flag (Sec.6.3)" @"
SELECT 'charges' AS src, dcd, COUNT(*) AS students, SUM(Charges) AS total FROM dbo.VIEW_OURM_CHARGES GROUP BY dcd
UNION ALL
SELECT 'credits', dcd, COUNT(*), SUM(credits) FROM dbo.VIEW_OURM_CREDITS GROUP BY dcd;
"@
Query "Transaction SOURCE_CDE distribution, current term (A-7)" "SELECT SOURCE_CDE, [STATUS], COUNT(*) AS n, SUM(CASE WHEN TRANS_AMT < 0 THEN 1 ELSE 0 END) AS negative_rows FROM dbo.VIEW_OURM_TRANS_HIST GROUP BY SOURCE_CDE, [STATUS] ORDER BY n DESC;" 100
Query "tblFCA_TRANS_HIST columns and SOURCE_CDE distribution" "SELECT SOURCE_CDE, COUNT(*) AS n FROM dbo.tblFCA_TRANS_HIST GROUP BY SOURCE_CDE ORDER BY n DESC;" 100
Query "Credits view row count" "SELECT COUNT(*) AS n FROM dbo.view_ourm_credits;"
Query "Charges view row count" "SELECT COUNT(*) AS n FROM dbo.view_ourm_charges;"

Out ""
Out "## 7. tblStudent aggregates (balances in aggregate only)"
Query "LastCleared distribution (term key format, A-16)" "SELECT LastCleared, COUNT(*) AS n FROM dbo.tblStudent GROUP BY LastCleared ORDER BY n DESC;" 100
Query "Balance sign distribution (Sec.9.2)" @"
SELECT SUM(CASE WHEN AccountBalance > 0 THEN 1 ELSE 0 END) AS positive_count,
       SUM(CASE WHEN AccountBalance > 0 THEN AccountBalance ELSE 0 END) AS positive_total,
       SUM(CASE WHEN AccountBalance < 0 THEN 1 ELSE 0 END) AS negative_count,
       SUM(CASE WHEN AccountBalance < 0 THEN AccountBalance ELSE 0 END) AS negative_total,
       SUM(CASE WHEN AccountBalance = 0 OR AccountBalance IS NULL THEN 1 ELSE 0 END) AS zero_or_null_count,
       COUNT(*) AS total_rows, COUNT(DISTINCT idnumber) AS distinct_students
FROM dbo.tblStudent;
"@
Query "Duplicate idnumber check in tblStudent" "SELECT COUNT(*) AS dup_keys FROM (SELECT idnumber FROM dbo.tblStudent GROUP BY idnumber HAVING COUNT(*) > 1) d;"

$conn.Close()

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$outFile = Join-Path $OutDir "ousadb-discovery-$stamp.md"
[IO.File]::WriteAllText($outFile, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Discovery written to $outFile"
